Support manual test state
reportportal/service-ui pull request #2537
Opened 2020-12-07 12:08 UTC by odubaj

2021-02-08 15:35 UTC, AmsterGet requested changes
Looks good.
Can be merged after:
- Returning the linter to the CI
- Resolving conflicts
- Backend implementation

2021-02-08 15:41 UTC, odubaj commented on Makefile
> -	npm --prefix $(UI_BUILD_REACT) run lint
probably just didn't wanted to run lint on each commit/build, removed only for testing reasons, will add it back

2021-02-08 15:41 UTC, odubaj commented on app/src/pages/inside/dashboardItemPage/modals/common/widgets.jsx
> +          'Shows statistics of the last launch divided into 2 sections:</br> - Skipped, Passed, Failed, Untested </br> - Product Bug, System Issue, To Investigate, Automation Bugs, Untested Test.'
probably just a bug, will remove

2021-02-08 16:14 UTC, odubaj commented
seems strange to me, I rebased my fork against current develop branch, then rebased UNTESTED commit according to your advices, but it does not seem to have updated this pull-request. fork to commit here: https://github.com/odubaj/service-ui/commits/develop

Maybe opening a new PR will be a silution ?

2021-02-08 18:03 UTC, odubaj commented
Seems to be some github API issue. Everything up-to-date now.

2021-03-31 20:56 UTC, AmsterGet commented
@odubaj Could you please resolve conflicts with the target branch?

2021-04-01 05:33 UTC, odubaj commented
> @odubaj Could you please resolve conflicts with the target branch?

Done

2021-07-16 11:35 UTC, chivekrodis commented
@odubaj Could you please update your fork to the latest, change target branch into `untested_test` and resolve conflicts if any?

2021-07-16 13:42 UTC, odubaj commented
Done, available in new PR:

https://github.com/reportportal/service-ui/pull/2768

2021-07-16 13:42 UTC, closed without merging