EPMRPP-59880 Add checkbox to the action panel
reportportal/service-ui pull request #2595
Opened 2021-02-26 07:38 UTC by katrin-kot

2021-02-26 08:16 UTC, ElenaRomanchuk commented on app/src/components/inputs/inputCheckbox/checkIcon/checkIcon.jsx
> +  <div className={cx('square', { centered, checked, disabled, ghost: ghostStyle })}>
I think it would be better to name prop `ghost` instead of `ghostStyle`.

2021-02-26 08:18 UTC, ElenaRomanchuk commented on app/src/components/inputs/inputCheckbox/checkIcon/checkIcon.scss
> +    border-color: $COLOR--topaz;
Is it OK that square will have the same border in all states: plain, hover, clicked? Have you discussed this with the designer?

2021-02-26 08:25 UTC, ElenaRomanchuk commented on app/src/components/inputs/inputCheckbox/inputCheckbox.jsx
> +  ghostStyle,
The same suggestion: `ghost` instead of `ghostStyle`

2021-02-26 08:41 UTC, ElenaRomanchuk requested changes

2021-02-26 08:41 UTC, ElenaRomanchuk commented on app/src/pages/inside/logsPage/logToolbar/logToolbar.jsx
> +            this.setState({ isChecked: !this.state.isChecked });
For now, it looks like this checkbox does nothing and will do nothing. Please, rename checkbox state according to its meaning. Also, expose checkbox state and onChange callback if they should be lifted to the parent component.

2021-02-26 08:59 UTC, ElenaRomanchuk requested changes

2021-02-26 08:59 UTC, ElenaRomanchuk commented on app/src/pages/inside/logsPage/logToolbar/logToolbar.jsx
> +          History Across All Launches
All messages in core UI should be localized.

2021-03-01 12:03 UTC, ElenaRomanchuk requested changes

2021-03-01 12:03 UTC, ElenaRomanchuk commented on app/src/pages/inside/logsPage/logToolbar/logToolbar.jsx
> +  checkboxLabel: {
Use meaningful name: `historyAllLaunchesLabel` or smth like this.

2021-03-01 12:42 UTC, ElenaRomanchuk approved these changes

2021-03-01 13:12 UTC, AmsterGet approved these changes

2021-03-01 13:12 UTC, merged