EPMRPP-59875 Add a new button to History Line
reportportal/service-ui pull request #2601
Opened 2021-03-03 11:19 UTC by katrin-kot

2021-03-03 21:02 UTC, ElenaRomanchuk requested changes

2021-03-03 21:02 UTC, ElenaRomanchuk commented on app/src/pages/inside/logsPage/historyLine/historyLine.jsx
> +                style={{
Most likely you need to reuse one of the existing button components. Overwise you should create the new one. I suggest to research if the needed component exists, overwise discuss with the designer are you really need a new one.
Never use inline styles unnecessarily.

2021-03-03 21:02 UTC, ElenaRomanchuk commented on app/src/pages/inside/logsPage/historyLine/historyLine.jsx
> +                  HISTORY_LINE_LOAD_MORE_BTN_TITLE
Use react-intl to localize messages and labels. Never hardcode them as a constant unnecessarily.

2021-03-04 11:25 UTC, AmsterGet requested changes

2021-03-04 11:25 UTC, AmsterGet commented on app/src/controllers/log/sagas.js
> +function* fetchMoreHistoryItems() {
Seems that this saga is too similar with `fetchHistoryItems` [saga](https://github.com/reportportal/service-ui/pull/2601/files#diff-f331d34263a8765d03a750f31a61d1d83cd24a2109cb6164d648eb1e72f62c52L111).
Can we reuse `fetchHistoryItems` saga to handle action with additional payload parameter (f.e. `loadMore: true`)?

2021-03-04 11:25 UTC, AmsterGet commented on app/src/pages/inside/logsPage/historyLine/historyLine.jsx
> +    const shouldShowLoadMore =
Will these conditions handle the case where the maximum allowed history depth is 30?

2021-03-05 07:57 UTC, AmsterGet commented on app/src/pages/inside/logsPage/historyLine/historyLine.jsx
> +    this.props.fetchMoreItemsHistoryAction(true);
Seems that this method always should fetch **more** history items, so please avoid misunderstandings and use one clear variant `fetchHistoryItemsAction({ loadMore: true })` or `fetchMoreHistoryItemsAction()`.

2021-03-05 07:57 UTC, AmsterGet commented on app/src/pages/inside/logsPage/historyLine/historyLine.scss
> +  font-weight: 600;
Please remove `font-weight` and use `$FONT-SEMIBOLD`

2021-03-05 07:57 UTC, AmsterGet commented on app/src/pages/inside/logsPage/historyLine/historyLine.scss
> +  &.active,
According to the component you don't use `.active` class name nowhere, so please remove this line.

2021-03-05 07:57 UTC, AmsterGet commented on app/src/controllers/log/sagas.js
> +  let historyDepth;
Why not just:
```
const historyDepth = payload
    ? countOfHistoryItems.length + NUMBER_OF_ITEMS_TO_LOAD
    : DEFAULT_HISTORY_DEPTH;
```

2021-03-05 07:57 UTC, AmsterGet commented on app/src/controllers/log/sagas.js
> +  const countOfHistoryItems = yield select(historyItemsSelector);
For now it is the `historyItems`, not the count of them.

2021-03-05 07:57 UTC, AmsterGet commented on app/src/pages/inside/logsPage/historyLine/historyLine.jsx
> +    this.setState({ isLoading: false });
It looks like this `loading` will be stopped before the response is received from BE.
For the fast fix I suggest to use a `callback` in the action to set `isLoading: false`, when the response will be received.

2021-03-05 13:26 UTC, AmsterGet commented
Closed in favor of https://github.com/reportportal/service-ui/pull/2606

2021-03-05 13:26 UTC, closed without merging