EPMRPP-45317  History table. Implemented the hover state for items without executions.
reportportal/service-ui pull request #2613
Opened 2021-03-12 08:34 UTC by katrin-kot

2021-03-12 09:45 UTC, chivekrodis approved these changes

2021-03-15 09:24 UTC, AmsterGet requested changes

2021-03-15 09:24 UTC, AmsterGet commented on app/src/pages/inside/historyPage/historyView/historyTable/emptyHistoryItem/emptyHistoryItem.jsx
> +      </EmptyHistoryItemTooltip>
You have added a tooltip for all content, but it is only required for item without executions (for [this](https://github.com/reportportal/service-ui/pull/2613/files#diff-f04b75348bbbd0050f74907b995ff1690087e60586b776f264379ecf00e23cc9R67) line)

2021-03-15 11:07 UTC, AmsterGet commented on app/src/pages/inside/historyPage/historyView/historyTable/emptyHistoryItem/emptyHistoryItem.jsx
> +    tooltipTriggerClass: cx('empty-history-item'),
This prop is redundant now - remove it please

2021-03-15 11:36 UTC, AmsterGet approved these changes

2021-03-15 11:36 UTC, merged