EPMRPP-53936 - fix integration pass field
reportportal/service-ui pull request #2618
Opened 2021-03-15 13:11 UTC by chivekrodis

2021-03-15 13:25 UTC, katrin-kot approved these changes

2021-03-16 10:16 UTC, AmsterGet requested changes

2021-03-16 10:16 UTC, AmsterGet commented on app/src/components/integrations/containers/integrationSettingsContainer/integrationSettingsContainer.jsx
> +    const integrationParameters = omit(data.integrationParameters, OMIT_KEYS);
Such `omit` already exists in the `src/controllers/plugins/sagas.js` `function* updateIntegration`.
To reuse this normalized `integrationParameters` make sense to provide integration data to the callback from the saga (line 127) and use it [here](https://github.com/reportportal/service-ui/pull/2618/files#diff-1b7acf2538fb238032aed222558b2f44ad5cb896602ad6bf286658e8cfb4908eR73).

2021-03-16 10:53 UTC, AmsterGet commented on app/src/components/integrations/containers/integrationSettingsContainer/integrationSettingsContainer.jsx
> +      (normalizeData) => {
`normalizeData` sounds like an action, may be name it just `updatedParameters` to use property shorthand?

2021-03-16 10:57 UTC, AmsterGet approved these changes

2021-03-16 10:58 UTC, merged