EPMRPP-60678 Add second step to the modal
reportportal/service-ui pull request #2646
Opened 2021-03-31 14:39 UTC by katrin-kot

2021-04-01 22:08 UTC, AmsterGet commented
@katrin-kot Please resolve conflicts!

2021-04-02 07:42 UTC, KatsiarynaTatarynovich requested changes

2021-04-02 07:42 UTC, KatsiarynaTatarynovich commented on app/src/pages/inside/stepPage/modals/editDefectModals/makeDecisionModal/makeDecisionModal.jsx
> +    setFormStep('configuration');
It's better to put `configuration` in a separate constant. The same for `options`.

2021-04-02 08:08 UTC, AmsterGet commented on app/src/pages/inside/stepPage/modals/editDefectModals/makeDecisionModal/makeDecisionModal.jsx
> +          {`< \u00A0 ${formatMessage(messages.backToConfiguration)}`}
Why we need special character here?

2021-04-02 13:40 UTC, chivekrodis approved these changes

2021-04-02 13:43 UTC, AmsterGet approved these changes

2021-04-02 13:44 UTC, merged