EPMRPP-60941 Fixed unlink action in bulk operation
reportportal/service-ui pull request #2651
Opened 2021-04-02 15:45 UTC by katrin-kot

2021-04-02 15:54 UTC, chivekrodis requested changes

2021-04-02 15:54 UTC, chivekrodis commented on app/src/controllers/groupOperations/utils.js
> +    const error = validator && validator(item, items, state);
Should we put items without external issues to unlink modal? We can omit them  in prepareDataToSend

2021-04-02 22:57 UTC, AmsterGet requested changes

2021-04-02 22:57 UTC, AmsterGet commented on app/src/controllers/step/actionCreators.js
> -  validateUnlinkIssue,
Your changes break the validation process for an independent `unlink` operation.
The existing validation should be left as is.

2021-04-05 07:55 UTC, AmsterGet approved these changes

2021-04-05 07:55 UTC, merged