EPMRPP-62781: decrease the space beetween buttons
reportportal/service-ui pull request #2729
Opened 2021-06-11 11:35 UTC by oranje322

2021-06-11 12:31 UTC, chivekrodis requested changes

2021-06-11 12:31 UTC, chivekrodis commented on app/src/components/buttons/ghostButton/ghostButton.scss
> +    }
What the purpose to create a new class and manage it with prop? Seems like we can add property directly to the `transparent-background` class.

2021-06-14 08:39 UTC, AmsterGet requested changes

2021-06-14 08:39 UTC, AmsterGet commented on app/src/pages/inside/stepPage/modals/postIssueModal/postIssueModal.jsx
> +          transparentLessWidth
Now it can be removed.

2021-06-14 09:27 UTC, AmsterGet approved these changes

2021-06-14 09:28 UTC, merged