EPMRPP-63388: GA Track events on sidebar/dashboards/adminproject
reportportal/service-ui pull request #2755
Opened 2021-07-06 10:43 UTC by oranje322

2021-07-06 12:17 UTC, chivekrodis requested changes

2021-07-06 12:17 UTC, chivekrodis commented on app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/controls/checkboxControl.jsx
> +    }
What the purpose use `!rest.value` if you have actual state in `event` object

2021-07-06 12:17 UTC, chivekrodis commented on app/src/pages/inside/dashboardItemPage/modals/common/widgetControls/productStatusControls.jsx
> +export const TO_INVESTIGATE = 'statistics$defects$to_investigate$ti001';
Maybe better move it to the closest constants file

2021-07-07 09:29 UTC, chivekrodis approved these changes

2021-07-08 08:06 UTC, KatsiarynaTatarynovich approved these changes

2021-07-08 10:48 UTC, merged