EPMRPP-64596: no ML options in make decision
reportportal/service-ui pull request #2799
Opened 2021-08-18 10:20 UTC by oranje322

2021-08-18 10:57 UTC, chivekrodis requested changes

2021-08-18 10:57 UTC, chivekrodis commented on app/src/pages/inside/stepPage/modals/makeDecisionModal/makeDecisionModal.jsx
> +    [MACHINE_LEARNING_SUGGESTIONS]: false,
For now if you open modal window ML tab closed by default.(no loader or something yet)
If it is expected behavior we do not needed anymore loading flag and loader component in `machineLearningSuggestions` component.
Also now if data loading long time user can  open ML tab manually and see `ML has not found any suggestions`, but data is in loading process and it is bad user experience.

2021-08-18 10:57 UTC, chivekrodis commented on app/src/pages/inside/stepPage/modals/makeDecisionModal/machineLearningSuggestions/machineLearningSuggestions.jsx
> +          href={'https://reportportal.io/docs/Deploy-Elastic-Search'}
Is it correct link? doc is empty

2021-08-18 11:38 UTC, oranje322 commented on app/src/pages/inside/stepPage/modals/makeDecisionModal/machineLearningSuggestions/machineLearningSuggestions.jsx
> +          href={'https://reportportal.io/docs/Deploy-Elastic-Search'}
correct, I think it should be fill soon

2021-08-20 08:20 UTC, chivekrodis approved these changes

2021-08-20 08:27 UTC, AmsterGet approved these changes

2021-08-20 08:27 UTC, merged