EPMRPP-63628: log view breadcrumbs max-width
reportportal/service-ui pull request #2801
Opened 2021-08-20 09:57 UTC by oranje322

2021-08-20 15:07 UTC, chivekrodis approved these changes

2021-08-23 11:22 UTC, AmsterGet requested changes

2021-08-23 11:22 UTC, AmsterGet commented on app/src/pages/inside/logsPage/logToolbar/logToolbar.scss
> +@media (max-width: $SCREEN_XL_MAX) {
Please remove it. Not need to add new screen size breakpoint.

2021-08-23 11:22 UTC, AmsterGet commented on app/src/pages/inside/logsPage/logToolbar/logToolbar.jsx
> +                  )}
As we need to use short label only on mobile, please use corresponding `SCREEN_XS_MAX` breadkpoint.

2021-08-23 11:22 UTC, AmsterGet commented on app/src/pages/inside/logsPage/logToolbar/logToolbar.jsx
> +                  )}
Also you may provide a custom class to `InputCheckbox` component to control wrappig behaviour. F.e. adding the CSS property `white-space: nowrap;` to this field will always keep all words in one line.

2021-08-23 11:22 UTC, AmsterGet commented on app/src/pages/inside/logsPage/logToolbar/logToolbar.scss
> +.breadcrumbs-wrapper {
After providing custom class to the `InputCheckbox` component it will be unnecessary.

2021-08-23 13:01 UTC, AmsterGet approved these changes

2021-08-23 13:01 UTC, merged