Epmrpp 68917
reportportal/service-ui pull request #2914
Opened 2021-11-18 11:20 UTC by oranje322

2021-11-18 18:55 UTC, chivekrodis requested changes

2021-11-18 18:55 UTC, chivekrodis commented on app/src/pages/inside/stepPage/modals/makeDecisionModal/elements/itemHeader/itemHeader.scss
> +  max-width: 90%;
Please recheck this solution for screen 768px and more. 
Also does it expected behavior for screen size 768-990px
![image](https://user-images.githubusercontent.com/42434528/142475667-5c3639c7-59bd-4123-9ad1-9b051858d1df.png)

2021-11-18 18:55 UTC, chivekrodis commented on app/src/pages/inside/stepPage/modals/makeDecisionModal/selectDefectManually/selectDefectManually.scss
> +  top: 105px;
Please align checkbox according markup(by text and right side)

2021-11-18 18:55 UTC, chivekrodis commented on app/src/pages/inside/stepPage/modals/makeDecisionModal/makeDecisionTabs/makeDecisionTabs.jsx
> +                      <div className={cx('icon')}>{Parser(ExternalLinkIcon)}</div>
Please do not put div element into p element is not valid layout

2021-11-18 18:55 UTC, chivekrodis commented on app/src/pages/inside/stepPage/modals/makeDecisionModal/makeDecisionTabs/makeDecisionTabs.scss
> +}
In my opinion is incorrect class name for padding equal 20px

2021-11-18 18:57 UTC, chivekrodis commented
![image](https://user-images.githubusercontent.com/42434528/142478980-c04e3d11-6fc6-4819-b253-f73dc9fe4862.png)
I guess animation should be removed not only if user click on first suggestion item and another too

2021-11-18 18:59 UTC, chivekrodis commented
Please align text by center for mid screen size
![image](https://user-images.githubusercontent.com/42434528/142479421-d827d816-859a-45f0-be4c-7d411ba89faf.png)

2021-11-19 08:23 UTC, AmsterGet commented
> ![image](https://user-images.githubusercontent.com/42434528/142478980-c04e3d11-6fc6-4819-b253-f73dc9fe4862.png) I guess animation should be removed not only if user click on first suggestion item and another too

No, we discussed with design team and the animation should be stopped only by click on the animated item.

2021-11-19 14:35 UTC, chivekrodis approved these changes

2021-11-19 14:41 UTC, AmsterGet approved these changes

2021-11-19 14:42 UTC, merged