EPMRPP-72995 || Add a new event "Quick Copy functionality" for Launches category
reportportal/service-ui pull request #2960
Opened 2021-12-27 14:17 UTC by Vadim73i

2021-12-27 16:01 UTC, chivekrodis approved these changes

2021-12-27 23:38 UTC, AmsterGet requested changes

2021-12-27 23:38 UTC, AmsterGet commented on app/src/components/main/analytics/events/common/testItemPages/modalEventsCreators.js
> +    label: 'Modal Edit Launch',
Should it be called `Modal Edit Item` when the event triggered from suites/tests/steps?

2021-12-28 08:39 UTC, AmsterGet approved these changes

2021-12-28 08:39 UTC, merged