EPMRPP-76246 || Refactoring for sign up extension
reportportal/service-ui pull request #3057
Opened 2022-04-06 15:13 UTC by tr1ble

2022-04-07 07:43 UTC, Vadim73i commented on app/src/pages/outside/loginPage/pageBlocks/loginBlock/loginBlock.jsx
> +        <div>
Maybe you can use react fragment instead <div>.

2022-04-08 12:26 UTC, AmsterGet commented on app/src/pages/outside/loginPage/pageBlocks/loginBlock/loginBlock.jsx
> +import { ExternalLoginBlock } from 'pages/outside/loginPage/pageBlocks/loginBlock/loginForm/externalLoginBlock';
please use relative path here:
`'./loginForm/externalLoginBlock'`

2022-04-11 12:40 UTC, chivekrodis requested changes

2022-04-11 12:40 UTC, chivekrodis commented on app/src/common/utils/getCurrentUrlParam.js
> +};
We have selector in page controller called `querySelector` which already exist and do the same thing. Please use it if it's fit

2022-04-12 08:56 UTC, Vadim73i approved these changes

2022-04-12 09:48 UTC, merged