EPMRPP-76489 || add project settings layout
reportportal/service-ui pull request #3063
Opened 2022-04-12 19:18 UTC by chivekrodis

2022-04-14 06:20 UTC, Vadim73i approved these changes

2022-04-15 08:34 UTC, AmsterGet requested changes

2022-04-15 08:34 UTC, AmsterGet commented on app/src/layouts/common/layout/layout.jsx
> +                  <div className={cx('header-container')}>
Please move header to a variable, as it duplicates two times and will be rendered in any case.

2022-04-15 08:34 UTC, AmsterGet commented on app/src/layouts/projectSettingsLayout/projectSettingsLayout.jsx
> +export const ProjectSettingsLayout = ({ navigation, children }) => (
Please rename it to just `SettingsLayout`. Hope it will be used for organization and instance settings as well.

2022-04-15 10:32 UTC, AmsterGet approved these changes

2022-04-15 10:33 UTC, merged