EPMRPP-76491 || project settings header
reportportal/service-ui pull request #3069
Opened 2022-04-14 15:40 UTC by chivekrodis

2022-04-14 17:40 UTC, tr1ble approved these changes

2022-04-15 07:29 UTC, Vadim73i approved these changes

2022-04-15 10:31 UTC, AmsterGet requested changes

2022-04-15 10:31 UTC, AmsterGet commented on app/src/pages/inside/projectSettingsPageContainer/projectSettingsPageContainer.jsx
> +  const header = useMemo(() => {
Is it necessary to memo such plain component?
You don't drill down it as a prop and it doesn't contain any calculations.

2022-04-15 13:31 UTC, AmsterGet reviewed
One more comment about `tabsConfig`, now we don't have tabs. Please rename to smth like `navConfig` or `pagesConfig` or smth like that.

2022-04-15 13:31 UTC, AmsterGet commented on app/src/pages/inside/projectSettingsPageContainer/projectSettingsPageContainer.jsx
> +        <div className={cx('header')}>{getHeader()}</div>
Why not just render the `<Header title={config[activeTab].name} />`?

2022-04-15 14:11 UTC, AmsterGet approved these changes

2022-04-15 14:11 UTC, AmsterGet commented
Please resolve conflicts.

2022-04-15 14:21 UTC, merged