EPMRPP-76495 || Button component
reportportal/service-ui pull request #3081
Opened 2022-04-27 15:16 UTC by oranje322

2022-04-27 15:20 UTC, tr1ble approved these changes

2022-04-28 09:07 UTC, chivekrodis requested changes

2022-04-28 09:07 UTC, chivekrodis commented on app/src/componentLibrary/button/button.scss
> +.text {
Please recheck text button according to design system it should be 22px height

2022-04-28 09:45 UTC, chivekrodis approved these changes

2022-04-28 13:29 UTC, AmsterGet approved these changes

2022-04-28 13:30 UTC, merged