EPMRPP-76889 || Registration styles fix
reportportal/service-ui pull request #3111
Opened 2022-05-25 10:03 UTC by tr1ble

2022-05-25 15:12 UTC, AmsterGet requested changes

2022-05-25 15:24 UTC, tr1ble commented on app/src/components/inputs/inputCheckbox/checkIcon/checkIcon.scss
> +    height: 24px;
I think yes, I think it won't make things worse because there was no styles for mobile/tablet

2022-05-27 07:59 UTC, AmsterGet approved these changes

2022-05-27 08:00 UTC, merged

2022-05-27 08:00 UTC, AmsterGet commented on app/src/components/inputs/inputCheckbox/checkIcon/checkIcon.scss
> +    height: 24px;
Decided to parametrize it to not broke other mockups.