EPMRPP-77582 || Long organization name fix
reportportal/service-ui pull request #3123
Opened 2022-06-06 10:27 UTC by tr1ble

2022-06-06 10:36 UTC, Vadim73i approved these changes

2022-06-06 10:57 UTC, chivekrodis requested changes

2022-06-06 10:57 UTC, chivekrodis commented on app/src/pages/admin/projectsPage/projectsPanelView/projectPanel/projectPanel.scss
> +  text-overflow: ellipsis;
As I remember, you should add title to provide ability see full name too

2022-06-07 07:53 UTC, chivekrodis approved these changes

2022-06-07 09:22 UTC, AmsterGet requested changes

2022-06-07 09:22 UTC, AmsterGet commented on app/src/pages/admin/projectsPage/projectsPanelView/projectPanel/projectPanel.jsx
> +              {this.getOrganization()}
If you call it twice here, move the calculated value to variable and reuse.

2022-06-07 11:01 UTC, merged