EPMRPP-78105 || Notifications preloader, EPMRPP-78115 || Modal window fix
reportportal/service-ui pull request #3162
Opened 2022-07-04 09:43 UTC by tr1ble

EPMRPP-78105 || Notifications preloader, EPMRPP-78115 || Modal window paddings fix

2022-07-04 11:47 UTC, chivekrodis requested changes

2022-07-04 11:53 UTC, tr1ble commented on app/src/componentLibrary/modal/modalLayout/modalLayout.scss
> +  padding: 32px 40px;
It's the task to fix it in new modal window so yes I guess that it's discussed

2022-07-04 12:07 UTC, chivekrodis requested changes

2022-07-04 12:07 UTC, chivekrodis commented on app/src/componentLibrary/modal/modalLayout/modalLayout.scss
> +  padding: 32px 40px;
Please discuss it with UX to make sure is everything is as expected

2022-07-04 12:08 UTC, chivekrodis commented on app/src/componentLibrary/modal/modalLayout/modalLayout.scss
> +  padding: 32px 40px;
Please discuss it with UX to make sure is everything is as expected

2022-07-05 08:24 UTC, AmsterGet requested changes

2022-07-05 08:24 UTC, AmsterGet commented on app/src/controllers/project/sagas.js
>    yield put(fetchProjectNotificationsSuccessAction(notifications));
May be `fetchDataAction` together with `fetchReducer` & `loadingReducer` can be used to cover all corner cases?

2022-07-05 09:01 UTC, tr1ble commented on app/src/componentLibrary/modal/modalLayout/modalLayout.scss
> +  padding: 32px 40px;
Yes, I've asked, everything is fine

2022-07-05 18:47 UTC, merged