EPMRPP-77854 || implement system message component
reportportal/service-ui pull request #3168
Opened 2022-07-06 13:12 UTC by RuslanLyubimov

2022-07-06 13:21 UTC, AmsterGet requested changes
Please leave only 1 commit related to the task.

2022-07-06 14:00 UTC, AmsterGet requested changes

2022-07-07 06:39 UTC, chivekrodis requested changes

2022-07-07 06:39 UTC, chivekrodis commented on app/src/componentLibrary/systemMessage/systemMessage.jsx
> +  children: PropTypes.string,
Please make children as a react node to have ability provide any type here

2022-07-07 06:39 UTC, chivekrodis commented on app/src/componentLibrary/systemMessage/systemMessage.jsx
> +import PropTypes from 'prop-types';
Please add standard license text here

2022-07-07 06:39 UTC, chivekrodis commented on app/src/componentLibrary/systemMessage/systemMessage.jsx
> +export const SystemMessage = ({ message, textSolution, children, mode }) => {
According to the task component should have 2 states
1. width should be according to content
2. width should be 100% of parent container

Do you provide this behaviour?

2022-07-07 06:39 UTC, chivekrodis commented on app/src/componentLibrary/systemMessage/systemMessage.scss
> +  box-shadow: 0px 1px 3px rgba(55, 67, 98, 0.1);
Please extract box-shadow to corresponding .scss file in common variables with name from design

2022-07-07 06:39 UTC, chivekrodis commented on app/src/componentLibrary/systemMessage/systemMessage.scss
> +  font-weight: 500;
font roboto with font-weight: 500 it is a $FONT-ROBOTO-MEDIUM
fw: 400 - $FONT-ROBOTO-REGULAR
fw: 500 - $FONT-ROBOTO-MEDIUM
fw: 700 - $FONT-ROBOTO-BOLD

2022-07-07 06:39 UTC, chivekrodis commented on app/src/componentLibrary/systemMessage/systemMessage.scss
> +      @include message-headers($COLOR--warning-message);
I cannot find naming for this color in DS pls discuss it with UX

2022-07-07 06:39 UTC, chivekrodis commented on app/src/componentLibrary/systemMessage/systemMessage.scss
> +@mixin font-config($weight, $size, $height, $color) {
Please add standard license text here

2022-07-07 12:38 UTC, RuslanLyubimov commented on app/src/common/css/variables/newColors.scss
> +$COLOR---system-error-message: #db3549;
Asked UX team, it will be corrected soon

2022-07-08 07:53 UTC, closed without merging

2022-07-08 07:57 UTC, AmsterGet commented
Closed in favor of https://github.com/reportportal/service-ui/pull/3171