EPMRPP-72320 || Remove ACL framework
reportportal/service-ui pull request #3187
Opened 2022-07-22 07:49 UTC by Vadim73i

2022-07-22 07:58 UTC, AmsterGet requested changes

2022-07-22 07:58 UTC, AmsterGet commented on app/src/pages/inside/dashboardPage/dashboardList/dashboardGrid/dashboardGrid.jsx
>            userDashboards
Seems like now it is not needed. Please remove.

2022-07-25 07:13 UTC, chivekrodis approved these changes

2022-07-25 23:14 UTC, AmsterGet approved these changes

2022-07-25 23:14 UTC, merged