EPMRPP-78274 || Upgrade react version to 17th
reportportal/service-ui pull request #3199
Opened 2022-07-26 10:46 UTC by Vadim73i

2022-07-26 11:35 UTC, chivekrodis reviewed
PR contains breaking changes
pipeline failed
tooltips(popper-js) are have wrong behaviour doesn't work or appear in the wrong place(f.e login page versions, select project, history)
upload btn broken
Looks like dashboards work inappropriate way(appearance, creating)
a lot of errors in the console

2022-08-03 11:59 UTC, chivekrodis requested changes
Please resolve conflicts
Have no possibility create Launch statistics chart
Edit Launch statistics chart leads to crash
Charts have strange behavior: widgets collapse in width after 1083px
Filter by start time on the launch page leads to crash app

2022-09-01 07:18 UTC, chivekrodis approved these changes

2022-09-19 20:05 UTC, AmsterGet commented on app/src/pages/admin/allUsersPage/allUsersGrid/projectsAndRolesColumn/projectsAndRolesColumn.jsx
> +          b: (data) => DOMPurify.sanitize(`<b>${data}</b>`),
Could you please explain this fix?
It is not clear.

2022-09-19 20:05 UTC, AmsterGet commented
Also please resolve conflicts.

2022-12-26 14:34 UTC, AmsterGet approved these changes

2022-12-26 14:39 UTC, merged