EPMRPP-78478 || Add events for Project Settings - Analyzer
reportportal/service-ui pull request #3200
Opened 2022-07-27 08:32 UTC by Bam6ycha

2022-07-28 11:05 UTC, chivekrodis requested changes

2022-07-31 16:44 UTC, chivekrodis requested changes

2022-08-01 11:22 UTC, chivekrodis requested changes

2022-08-01 11:22 UTC, chivekrodis commented on app/src/components/main/analytics/utils.js
> +export const normalizeEventType = (type) => type.replace(/\s/g, '_').toLocaleLowerCase();
Looks unnecessary anymore

2022-08-01 13:56 UTC, chivekrodis approved these changes

2022-08-02 09:34 UTC, AmsterGet approved these changes

2022-08-02 09:34 UTC, merged