EPMRPP-78479 || Add events for Project Settings - Notifications
reportportal/service-ui pull request #3205
Opened 2022-07-29 11:41 UTC by Bam6ycha

2022-08-03 07:42 UTC, chivekrodis requested changes

2022-08-03 07:42 UTC, chivekrodis commented on app/src/pages/inside/projectSettingsPageContainer/content/emptyStatePage/emptyStatePage.jsx
> +  analyticsTrigger,
Please use common name like documintationClickHandler os similar to it

2022-08-03 07:42 UTC, chivekrodis commented on app/src/pages/inside/projectSettingsPageContainer/content/notifications/notifications.jsx
>          : SETTINGS_PAGE_EVENTS.TURN_OFF_NOTIFICATION_RULE_SWITCHER,
Please remove old events

2022-08-05 05:30 UTC, chivekrodis requested changes

2022-08-05 05:30 UTC, chivekrodis commented on app/src/pages/inside/projectSettingsPageContainer/content/elements/ruleList/ruleItem/ruleItem.jsx
> +    onClick(shown);
Right now it works on close but should be on open

2022-08-05 07:12 UTC, chivekrodis approved these changes

2022-08-05 07:28 UTC, AmsterGet approved these changes

2022-08-05 07:28 UTC, merged