EPMRPP-78271 || add multipleAutocomplite component
reportportal/service-ui pull request #3237
Opened 2022-08-19 15:57 UTC by chivekrodis

2022-08-21 17:02 UTC, tr1ble commented on app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleDownshift.jsx
> +export class MultipleDownshift extends Component {
Why is not a functional component ?

2022-08-21 22:39 UTC, tr1ble approved these changes

2022-08-22 09:42 UTC, Vadim73i requested changes

2022-08-22 09:42 UTC, Vadim73i commented on app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleDownshift.jsx
> +    return {
FYI: simplify return to ()

2022-08-22 09:42 UTC, Vadim73i commented on app/src/componentLibrary/autocompletes/multipleAutocomplete/selectedItems/selectedItems.jsx
> +    <>
FYI: Is fragment really needed here?

2022-08-22 09:42 UTC, Vadim73i commented on app/src/pages/inside/projectSettingsPageContainer/content/notifications/modals/addEditNotificationModal/launchNamesContainer/launchNamesContainer.jsx
> +  };
setShowMessage(items.length !== Object.keys(storedItems).length)

2022-08-22 11:49 UTC, chivekrodis commented on app/src/componentLibrary/autocompletes/multipleAutocomplete/selectedItems/selectedItems.jsx
> +    <>
removed

2022-08-22 11:51 UTC, chivekrodis commented on app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleAutocomplete.jsx
> +          <div>
It is downshift requirement as children should contains only one child

2022-08-22 11:51 UTC, chivekrodis commented on app/src/common/utils/validation/validate.js
> +  }
I have using built in config. Can you provide some more info

2022-08-22 11:52 UTC, chivekrodis commented on app/src/common/utils/validation/validate.js
> +  const re = /[.@]/;
re is a regular expression
regex return a new function and I pass it as a function to some method
I have refactored it lil bit

2022-08-22 13:38 UTC, Vadim73i approved these changes

2022-08-22 13:39 UTC, merged