EPMRPP-79057 || Defect  types GA4 events
reportportal/service-ui pull request #3250
Opened 2022-09-01 11:02 UTC by tr1ble

2022-09-01 14:09 UTC, Vadim73i requested changes

2022-09-01 14:09 UTC, Vadim73i commented on app/src/components/main/analytics/events/ga4Events/projectSettingsPageEvents.js
> +    element_name: 'icon_copy',
icon_name instead of element_name

2022-09-01 14:09 UTC, Vadim73i commented on app/src/components/main/analytics/events/ga4Events/projectSettingsPageEvents.js
> +    element_name: 'icon_create_defect',
icon_name instead of element_name

2022-09-01 18:33 UTC, Vadim73i approved these changes

2022-09-02 08:58 UTC, tr1ble commented on app/src/pages/inside/projectSettingsPageContainer/content/defectTypes/defectTypes.jsx
> +  };
Thanks!

2022-09-02 09:33 UTC, chivekrodis approved these changes

2022-09-02 09:33 UTC, merged