EPMRPP-79188 || Implement popover component
reportportal/service-ui pull request #3260
Opened 2022-09-15 13:20 UTC by Vadim73i

2022-09-15 17:09 UTC, tr1ble approved these changes

2022-10-03 23:20 UTC, AmsterGet requested changes

2022-10-03 23:20 UTC, AmsterGet commented on app/src/componentLibrary/popover/README.md
> +- **dataAutomationId**: _string_, optional, default = ''
Please update readme according to the new naming.

2022-10-03 23:20 UTC, AmsterGet commented on app/src/componentLibrary/popover/withPopover/withPopover.jsx
> +          }}
Are you sure that `WrappedComponent` will receive such props? Why not to handle click on parent `div`?
Please also don't forget to provide `{...props}` from the last anonymous function to the `WrappedComponent` as it is wrapped by HOC.

2022-10-03 23:20 UTC, AmsterGet commented on app/src/componentLibrary/popover/withPopover/withPopover.jsx
> +  WrappedComponent: PropTypes.element.isRequired,
`withPopover` is not a component, it's plain function.

2022-10-03 23:20 UTC, AmsterGet commented on app/src/componentLibrary/popover/withPopover/withPopover.jsx
> +export const withPopover = ({ content, ...props }) => (WrappedComponent) => () => {
It's not a `props`. Please rename to f.e. `popoverConfig`.

2022-10-04 07:56 UTC, AmsterGet commented on app/src/componentLibrary/popover/withPopover/withPopover.jsx
> +}) => {
Why not just `(props) => ...`?

2022-10-04 08:09 UTC, AmsterGet approved these changes

2022-10-04 08:09 UTC, merged