EPMRPP-79221 || Default Defect Type color on group select fix, EPMRPP-79165 || Color picker background color fix
reportportal/service-ui pull request #3263
Opened 2022-09-16 08:39 UTC by tr1ble

2022-09-19 06:59 UTC, Vadim73i commented
Are you sure you fixed "Selector in color picker is bigger than on Mock-ups"?

2022-09-19 08:47 UTC, tr1ble commented
> Are you sure you fixed "Selector in color picker is bigger than on Mock-ups"?

I set size of it accroding to Mock-up long time ago

2022-09-19 08:59 UTC, Vadim73i approved these changes

2022-09-19 18:16 UTC, chivekrodis commented on app/src/components/main/hexColorPicker/hexColorPicker.scss
> +}
Please make sure that solution doesn't affected each section in the app

2022-09-19 20:56 UTC, AmsterGet requested changes

2022-09-19 23:21 UTC, tr1ble commented on app/src/pages/inside/projectSettingsPageContainer/content/defectTypes/modals/addEditDefectTypeModal/addEditDefectTypeModal.jsx
> +            change(COLOR_FIELD_KEY, value);
I'be tried without it, but it didn't work for some reason. I'ok try again

2022-09-20 06:51 UTC, AmsterGet approved these changes

2022-09-20 06:51 UTC, merged