EPMRPP-79056 || Add events for Integrations
reportportal/service-ui pull request #3272
Opened 2022-09-22 16:32 UTC by RuslanLyubimov

2022-09-23 06:09 UTC, Bam6ycha requested changes

2022-09-23 06:09 UTC, Bam6ycha commented on app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationInfo.jsx
> +    trackEvent(PROJECT_SETTINGS_INTEGRATION.CLICK_RESET_TO_GLOBAL_INEGRATION);
Here is the same.

2022-09-23 07:27 UTC, Bam6ycha approved these changes

2022-09-26 11:16 UTC, chivekrodis approved these changes

2022-09-27 07:33 UTC, AmsterGet approved these changes

2022-09-27 07:33 UTC, merged