EPMRPP-79185 || remove extra button if haven't integrations
reportportal/service-ui pull request #3345
Opened 2022-11-25 08:43 UTC by KrasovskyAlexander

[EPMRPP-79185](https://jiraeu.epam.com/browse/EPMRPP-79185) 
Don't show extra button in header if haven't integrations
---
Before: 
![image](https://user-images.githubusercontent.com/70880574/203937916-1529c95a-2b81-42bf-9b4f-37f853d054bf.png)

---
After: 
![Screenshot_146](https://user-images.githubusercontent.com/70880574/203937797-6bdbfa79-cb77-4fbc-9fcd-5cac800c8b18.png)
![Screenshot_147](https://user-images.githubusercontent.com/70880574/203937838-0dd0adb4-a0f1-4ee0-983d-c4869f010050.png)

---

2022-11-25 09:27 UTC, chivekrodis requested changes

2022-11-25 09:27 UTC, chivekrodis commented on app/src/pages/inside/projectSettingsPageContainer/content/integrations/integrationsList/integrationInfo/integrationInfo.jsx
>              withButton
I guess you can set `withButton={isAvailableLeastOneIntegration}` and that's it without passing the new props

2022-11-28 10:37 UTC, chivekrodis approved these changes

2022-11-28 10:39 UTC, Bam6ycha approved these changes

2022-11-28 11:11 UTC, AmsterGet approved these changes

2022-11-28 11:11 UTC, merged