EPMRPP-79270 || remove placeholder if recipient added
reportportal/service-ui pull request #3366
Opened 2022-12-26 04:19 UTC by KrasovskyAlexander

[EPMRPP-79270](https://jiraeu.epam.com/browse/EPMRPP-79270)

Before: 
![image](https://user-images.githubusercontent.com/70880574/209499372-7a4d4a93-3a4e-4158-a09f-70af1d99c5df.png)

---
After: 
![Screenshot_163](https://user-images.githubusercontent.com/70880574/209499360-61a6c645-71f8-4b4d-a9e9-aedfab7a438b.png)

---

2022-12-26 07:43 UTC, AmsterGet requested changes
Do we need to hide the placeholder for launch names as well? Please confirm with QA team.

![image](https://user-images.githubusercontent.com/31861805/209519689-f0349820-c74d-464f-a7a7-45e72b64dfa3.png)

If yes, I suppose that better to make a fix inside of `AsyncMultipleAutocomplete` to keep components behavior the same.

2022-12-27 06:52 UTC, KrasovskyAlexander commented
@AmsterGet you correct!
![Screenshot_166](https://user-images.githubusercontent.com/70880574/209624487-5ee97515-1d1c-4cb8-b022-9019913ab798.png)
fixed ✅

2022-12-27 07:23 UTC, AmsterGet approved these changes

2022-12-27 07:23 UTC, AmsterGet approved these changes

2022-12-27 07:23 UTC, merged