EPMRPP-81141 || hidden manage buttons when user without manage permissions
reportportal/service-ui pull request #3377
Opened 2023-01-13 06:24 UTC by KrasovskyAlexander

[EPMRPP-81141](https://jiraeu.epam.com/browse/EPMRPP-81141)
hidden manage buttons when user without manage permissions

2023-01-13 08:48 UTC, AmsterGet requested changes

2023-01-13 08:48 UTC, AmsterGet commented on app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.jsx
> +          {this.props.userProjectRole === PROJECT_MANAGER && (
Please use common permissions engine - `canUpdateSettings` from `'common/utils/permissions'`.
Usage example - `src/pages/common/settingsPage/autoAnalysisTab/autoAnalysisTab.jsx`.

2023-01-20 09:33 UTC, KrasovskyAlexander commented on app/src/components/integrations/elements/integrationSettings/connectionSection/connectionSection.jsx
> +          {this.props.userProjectRole === PROJECT_MANAGER && (
fixed ✓

2023-01-20 09:43 UTC, Bam6ycha approved these changes

2023-01-20 09:59 UTC, AmsterGet approved these changes

2023-01-20 10:00 UTC, merged