EPMRPP-81506 || Implement Datepicker
reportportal/service-ui pull request #3399
Opened 2023-02-02 13:19 UTC by Bam6ycha

2023-02-03 14:09 UTC, Vadim73i approved these changes

2023-02-03 14:57 UTC, AmsterGet commented on app/src/componentLibrary/datePicker/README.md
> +- **value** : _string_, optional, default = new Date()
I don't see the default `value` in the `DatePicker.defaultProps`.

2023-02-07 06:13 UTC, AmsterGet requested changes

2023-02-07 06:13 UTC, AmsterGet commented on app/src/componentLibrary/datePicker/header/datePickerHeader.jsx
> +  const mothsDropdownOptions = useMemo(
month

2023-02-07 08:59 UTC, AmsterGet requested changes
Also please update message ids for Chinese localization

2023-02-07 08:59 UTC, AmsterGet commented on app/src/componentLibrary/datePicker/header/datePickerHeader.jsx
> +);
Can you extract the months simpler?
F.e. like here

![image](https://user-images.githubusercontent.com/31861805/217198462-456f6511-bbcc-4714-a140-99f74afef00c.png)

2023-02-07 08:59 UTC, AmsterGet commented on app/src/componentLibrary/datePicker/header/datePickerHeader.jsx
> +  const mothDropdownOptions = useMemo(
month

2023-02-07 08:59 UTC, AmsterGet commented on app/src/componentLibrary/datePicker/header/datePickerHeader.jsx
> +  const currentMothDisplayed = mothDropdownOptions[currentMonth];
month

2023-02-07 14:43 UTC, merged