EPMRPP-82176 || Long attributes are not truncated in tooltip on launch history, logs view
reportportal/service-ui pull request #3441
Opened 2023-03-29 08:59 UTC by Vadim73i

2023-03-29 12:50 UTC, Bam6ycha requested changes

2023-03-30 16:20 UTC, Bam6ycha commented on app/src/pages/inside/logsPage/historyLine/historyLineItem/historyLineItemTooltip/historyLineItemTooltip.jsx
> +                {attribute.key && <span className={cx('attribute-item-separator')}>:</span>}
we can simplify    
             `{attribute.key && (
                  <>
                    <span className={cx('attribute-item-key')}>{attribute.key}</span>
                    <span className={cx('attribute-item-separator')}>:</span>
                  </>
                )}
                <span className={cx('attribute-item-value')}>{attribute.value}</span>`

2023-03-30 16:21 UTC, Bam6ycha commented on app/src/pages/inside/logsPage/historyLine/historyLineItem/historyLineItemTooltip/historyLineItemTooltip.scss
> +  width: fit-content;
here we need only max-width and white space properties.

2023-03-30 16:30 UTC, Bam6ycha commented on app/src/pages/inside/logsPage/historyLine/historyLineItem/historyLineItemTooltip/historyLineItemTooltip.scss
> +    width: fit-content;
we do not need it here.

2023-03-31 06:54 UTC, Bam6ycha approved these changes

2023-03-31 07:35 UTC, AmsterGet approved these changes

2023-03-31 07:35 UTC, merged