EPMRPP-83121 || Implement the API KEYS tab view (Create/Revoke modals)
reportportal/service-ui pull request #3474
Opened 2023-05-17 20:33 UTC by Vadim73i

2023-05-18 09:01 UTC, AmsterGet commented on app/src/pages/inside/profilePage/modals/revokeApiKeyModal/revokeApiKeyModal.jsx
> +        onSuccess: () => closeModal(),
```suggestion
        onSuccess: closeModal,
```

2023-05-18 09:05 UTC, Bam6ycha requested changes

2023-05-22 08:57 UTC, Bam6ycha commented on app/src/controllers/user/sagas.js
> +    yield put(fetchApiKeysAction());
I am not sure, that we need to fetch all APIKeys. As I understand correctly we already have has all keys.
We store all keys in our store, and when we create new key, we can just add new key to the our store.

2023-05-22 08:58 UTC, Bam6ycha commented on app/src/controllers/user/sagas.js
> +    yield put(fetchApiKeysAction());
Here is the same

2023-05-23 10:18 UTC, AmsterGet requested changes

2023-05-23 10:18 UTC, AmsterGet commented on app/src/controllers/user/sagas.js
> +    yield put(setApiKeysAction(updatedApiKeys));
Please move this logic to the reducer.
Create a separate action handlers to address such actions.

2023-05-23 10:18 UTC, AmsterGet commented on app/src/controllers/user/sagas.js
> +    const { id, name: newName, created_at, api_key } = response;
You can use the name from the `payload` as they are the same.

2023-05-23 10:18 UTC, AmsterGet commented on app/src/controllers/user/sagas.js
> +    yield put(setApiKeysAction(updatedApiKeys));
Move to the reducer.

2023-05-23 10:57 UTC, Bam6ycha requested changes

2023-05-23 10:57 UTC, Bam6ycha commented on app/src/pages/inside/profilePage/apiKeys/apiKeysBlock/apiKeysBlock.jsx
> +                    color={'red'}
we can omit curly braces here.

2023-05-23 13:39 UTC, Bam6ycha requested changes

2023-05-23 13:39 UTC, Bam6ycha commented on app/src/controllers/user/sagas.js
> +    yield put(setApiKeysAction(response.items.sort((a, b) => b.created_at - a.created_at)));
can we move this logic to reducer?

2023-05-23 14:11 UTC, AmsterGet approved these changes

2023-05-23 14:11 UTC, AmsterGet approved these changes

2023-05-23 14:12 UTC, merged