EPMRPP-83221 || update the links on project settings pages connected to data privacy
reportportal/service-ui pull request #3481
Opened 2023-05-25 15:31 UTC by Vadim73i

2023-05-26 07:19 UTC, AmsterGet requested changes

2023-05-26 07:19 UTC, AmsterGet commented on app/src/layouts/settingsLayout/settingsLayout.jsx
> +        <div className={cx('footer')}>
Please move this Layout's footer to its own component.

2023-05-26 07:19 UTC, AmsterGet commented on app/src/layouts/settingsLayout/settingsLayout.jsx
> +    </a>,
You can build that elements during config mapping and left only messages and links in the config.

2023-05-26 07:19 UTC, AmsterGet commented on app/src/layouts/settingsLayout/settingsLayout.jsx
> +    defaultMessage: '© Report Portal 2023 All rights reserved',
Do not hardcode the actual year value.

2023-05-29 08:32 UTC, Bam6ycha requested changes

2023-05-29 08:32 UTC, Bam6ycha commented on app/src/layouts/settingsLayout/footer/footer.jsx
> +export const Footer = connect((state) => ({
Clould you explain, why we are using `connect` here?
My suggestion is to rewrite it to hooks.
Connect works differently from useSelector, but in this case it does not metter.

2023-05-29 08:32 UTC, Bam6ycha commented on app/src/layouts/settingsLayout/settingsLayout.jsx
Remove empty line.

2023-05-29 08:55 UTC, AmsterGet requested changes

2023-05-29 08:55 UTC, AmsterGet commented on app/src/layouts/settingsLayout/footer/footer.jsx
> +  const currentYear = date.getFullYear();
It looks like the date is not actually a prop and is never passed through props.
Why not calculate the actual year right here?

```suggestion
  const currentYear = (new Date()).getFullYear();
```

2023-05-29 09:14 UTC, AmsterGet approved these changes

2023-05-29 09:15 UTC, Bam6ycha approved these changes

2023-05-29 09:16 UTC, merged