EPMRPP-81639 || User cannot enter the whole username in "Recipients" field on "Notifications" tab
reportportal/service-ui pull request #3495
Opened 2023-06-06 13:17 UTC by Vadim73i

2023-06-07 07:39 UTC, Bam6ycha requested changes

2023-06-07 07:39 UTC, Bam6ycha commented on app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleAutocomplete.jsx
> +                    value.indexOf(item) < 0 &&
Could we give this expression a more descriptional name?
It is absolutely hard to figure out what we are doing here.
And, after that, maybe we could find an easier way to handle this scenario.

2023-06-08 15:14 UTC, AmsterGet commented on app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleAutocomplete.jsx
> +                });
If there are no concerns, I suggest to left simple condition here:
```javascript
const filteredOptions = options.filter((item) => value.indexOf(item) < 0);
```
I didn't find any reasons for excluding the options with same value as typed in input.

2023-06-09 09:30 UTC, AmsterGet commented on app/src/componentLibrary/autocompletes/multipleAutocomplete/multipleAutocomplete.jsx
> +  duplicateInputValueOption,
Please remove the prop as it is no longer in use.

2023-06-09 09:48 UTC, AmsterGet approved these changes

2023-06-09 09:50 UTC, Bam6ycha approved these changes

2023-06-09 09:51 UTC, merged