EPMRPP-81758 || Project settings.Notifications. Long attribute should be displayed shortened with 3 dots
reportportal/service-ui pull request #3496
Opened 2023-06-06 14:33 UTC by Vadim73i

2023-06-07 06:47 UTC, Bam6ycha approved these changes

2023-06-09 09:28 UTC, AmsterGet requested changes

2023-06-09 10:27 UTC, AmsterGet commented on app/src/componentLibrary/attributeList/editableAttribute/attribute/attribute.jsx
> +          <div className={cx('value-without-key')}>{attribute.value}</div>
Decided to fix it in the scope of EPMRPP-80693.

2023-06-09 10:28 UTC, AmsterGet approved these changes

2023-06-09 10:28 UTC, merged