EPMRPP-84533 || Login with SAML. The error message is displayed 2 times in case user logs in via SAML with already existing email
reportportal/service-ui pull request #3508
Opened 2023-06-26 11:44 UTC by Vadim73i

2023-06-26 12:28 UTC, Bam6ycha approved these changes

2023-06-26 13:23 UTC, AmsterGet requested changes

2023-06-26 13:23 UTC, AmsterGet commented on app/src/pages/outside/loginPage/loginPage.jsx
>      }
You can move this block into method and call it twice instead of duplicating the same logic.

2023-06-27 05:44 UTC, AmsterGet approved these changes

2023-06-27 05:44 UTC, merged