EPMRPP-79123 || Add tooltip to disabled "Create Rule" button when Email Server integration is not configured
reportportal/service-ui pull request #3542
Opened 2023-07-24 15:37 UTC by Vadim73i

2023-07-24 15:54 UTC, Bam6ycha requested changes

2023-07-24 15:54 UTC, Bam6ycha commented on app/src/pages/inside/projectSettingsPageContainer/content/notifications/messages.js
> +    id: 'ButtonTooltip.notConfiguredTooltip',
Let's rename it to something more specific. Because this tooltip message is only used in Notifications tab.

2023-07-24 15:54 UTC, Bam6ycha commented on app/src/pages/inside/projectSettingsPageContainer/content/notifications/notifications.jsx
> +            <CreateButton name={formatMessage(messages.create)} onClick={onAdd} />
From my point of view, this component is redundant. Actually, he does nothing.
That is why I suggest is to remove it, and use the Button component directly.

2023-07-24 15:54 UTC, Bam6ycha commented on app/src/pages/inside/projectSettingsPageContainer/content/emptyStatePage/emptyStatePage.jsx
> +            onClick={handleButton}
If the button is disabled, actually we do not need the event handler.

2023-07-25 08:23 UTC, Bam6ycha approved these changes

2023-07-25 08:47 UTC, AmsterGet requested changes

2023-07-25 08:47 UTC, AmsterGet commented on app/src/pages/inside/projectSettingsPageContainer/content/notifications/notifications.jsx
> +})(CreateButton);
Can we use just `Button` here?

2023-07-25 08:47 UTC, AmsterGet commented on app/src/pages/inside/projectSettingsPageContainer/content/emptyStatePage/emptyStatePage.jsx
> +})(EmptyStateButton);
Same here.

2023-07-25 08:59 UTC, AmsterGet approved these changes

2023-07-25 08:59 UTC, merged