EPMRPP-85843 || Add API Key Link to documentation on Profile page
reportportal/service-ui pull request #3587
Opened 2023-09-13 10:10 UTC by BlazarQSO

2023-09-13 14:03 UTC, Bam6ycha requested changes

2023-09-13 14:03 UTC, Bam6ycha commented on app/src/pages/inside/profilePage/apiKeys/apiKeysBlock/apiKeysBlock.scss
>    margin-bottom: 24px;
Please, add line-height property here

2023-09-14 09:48 UTC, BlazarQSO commented on app/localization/translated/uk.json
> +  "ApiKeys.ApiKeysBlock.descriptionLink": "Документації",
Done.

2023-09-14 09:49 UTC, BlazarQSO commented on app/src/pages/inside/profilePage/apiKeys/apiKeysBlock/apiKeysBlock.scss
> +  text-decoration: none;
Done.

2023-09-14 09:49 UTC, BlazarQSO commented on app/src/pages/inside/profilePage/apiKeys/apiKeysBlock/apiKeysBlock.scss
> +  max-width: 780px;
Done.

2023-09-14 09:51 UTC, Bam6ycha approved these changes

2023-09-14 10:42 UTC, AmsterGet approved these changes

2023-09-14 10:42 UTC, merged