EPMRPP-83572 || Update the view of Notification rule with attributes
reportportal/service-ui pull request #3636
Opened 2023-11-03 09:17 UTC by Vadim73i

2023-11-03 13:59 UTC, AmsterGet requested changes

2023-11-03 13:59 UTC, AmsterGet commented on app/src/pages/inside/projectSettingsPageContainer/content/elements/notificationRuleContent/notificationRuleContent.jsx
> +import { ATTRIBUTES_OPERATORS } from 'pages/common/settingsPage/notificationsTab/constants';
Please use corresponding constants from the redesigned components (import from '../../notifications/constants' as below).

2023-11-03 13:59 UTC, AmsterGet commented on app/src/pages/inside/projectSettingsPageContainer/content/elements/notificationRuleContent/notificationRuleContent.jsx
> +              : formatMessage(messages.attributesLabel)}
Please move to a variable or function to simplify reading.

2023-11-03 13:59 UTC, AmsterGet commented on app/src/components/containers/AttributeListFormField/attributeListFormField.jsx
> +        : attributesNote || formatMessage(messages.attributesNote);
Looks like we'll provide custom `attributesNote` for all cases except the notifications tab. And if it is not provided, we'll face the bug that notifications related message shown for not only notifications related use cases.
So please lets move this specific message to the parent component and provide it via `attributesNote` prop.

2023-11-06 08:54 UTC, Bam6ycha requested changes

2023-11-06 08:54 UTC, Bam6ycha commented on app/src/pages/inside/projectSettingsPageContainer/content/elements/notificationRuleContent/notificationRuleContent.jsx
> +  const { informOwner, recipients, attributes, attributesOperator, launchNames, sendCase } = item;
Looks like we can destructure it directly in func arguments

2023-11-06 09:49 UTC, AmsterGet requested changes
Please also fix SonarCloud issue

![image](https://github.com/reportportal/service-ui/assets/31861805/2995b817-683c-4b8b-91a0-09a05a4ab05a)

2023-11-06 09:49 UTC, AmsterGet commented on app/src/pages/inside/projectSettingsPageContainer/content/elements/notificationRuleContent/notificationRuleContent.jsx
> +            : formatMessage(messages.attributesLabelAny)
`formatMessage(attributesOperator === ATTRIBUTES_OPERATORS.AND ? messages.attributesLabelAll : messages.attributesLabelAny)`

2023-11-06 14:19 UTC, AmsterGet approved these changes

2023-11-06 14:39 UTC, merged