EPMRPP-87738 || Update event Apply for Make decision
reportportal/service-ui pull request #3680
Opened 2023-11-30 18:07 UTC by Bam6ycha

2023-12-01 14:57 UTC, BlazarQSO approved these changes

2023-12-04 11:21 UTC, AmsterGet requested changes

2023-12-04 11:21 UTC, AmsterGet commented on app/src/pages/inside/stepPage/modals/makeDecisionModal/constants.js
> +};
Can we just update the string values for `SELECT_DEFECT_MANUALLY`, `COPY_FROM_HISTORY_LINE`, `MACHINE_LEARNING_SUGGESTIONS` and use them directly?

2023-12-04 14:07 UTC, AmsterGet approved these changes

2023-12-04 14:07 UTC, merged